version: 2

project_name: kube-why

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: kube-why
    repository:
      owner: Ayushmore1214
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/Ayushmore1214/kube-why"
    description: "Look up what a Kubernetes error means and how to fix it, from your terminal."
    license: "MIT"
